=== hmcts/cpp-context-work-management-proxy/work-management-proxy-api/src/raml/json/schema/workmanagementproxy.create-custom-task.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://moj.gov.uk/cps/workmanagement/proxy/api/workmanagementproxy.create-custom-task.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "displayName": {
      "type": "string"
    },
    "taskName": {
      "type": "string"
    },
    "taskType": {
      "type": "string"
    },
    "due": {
      "type": "string"
    },
    "caseURN": {
      "type": "string"
    },
    "assignee": {
      "type": "string"
    },
    "candidateGroups": {
      "type": "string"
    },
    "isDeletable": {
      "type": "boolean"
    },
    "isDeferrable": {
      "type": "boolean"
    },
    "caseId": {
      "type": "string"
    },
    "caseTag": {
      "type": "string"
    },
    "businessUnitCodes": {
      "type": "string"
    },
    "courtCodes": {
      "type": "string"
    },
    "isUrgent": {
      "type": "boolean"
    },
    "defendants": {
      "type": "array",
      "items": {
        "$ref": "http://moj.gov.uk/cps/workmanagement/proxy/api/defendant.json"
      }
    },
    "comment": {
      "type": "string"
    },
    "note": {
      "type": "string"
    },
    "noteLastUpdatedDate": {
      "type": "string"
    },
    "noteLastUpdatedUser": {
      "type": "string"
    },
    "hearingDate": {
      "type": "string"
    }

  },
  "required": [
    "caseURN",
    "courtCodes"
  ]
}

=== hmcts/cpp-context-work-management-proxy/work-management-proxy-api/src/raml/json/workmanagementproxy.create-custom-task.json
{
  "displayName": "Check phone call2",
  "taskName": "customTask1",
  "taskType": "assignment",
  "due": "2021-11-03T23:59:00.000Z",
  "caseURN": "29GD7875621",
  "assignee": "checkOuCodeLogic",
  "candidateGroups": "dadsada",
  "isDeletable": true,
  "isDeferrable": true,
  "caseId": "8e4b2be0-f92a-4291-9b99-17af7e645472",
  "businessUnitCodes": "businessUnitOuCode",
  "courtCodes": "courtOuCode",
  "isUrgent": false,
  "defendants": [{"id": "1", "firstName": "Smith", "lastName": "Philip"},
    {"id": "2", "firstName": "Mona", "lastName": "Lisa"},
    {"id": "3", "firstName": "Victor", "lastName": "Hugo"},
    {"id": "4", "firstName": "Leo", "lastName": "Tolstoy"}],
  "comment": "This is test comment",
  "noteLastUpdatedDate": "2021-11-03T23:59:00.000Z",
  "noteLastUpdatedUser": "Erica Wilson"
}
